In [1]:
import numpy as np

matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Mengakses baris pertama
first_row = matrix[0, :]

first_row

array([1, 2, 3])

In [6]:
matrix_1 = np.array([
  [1, 2],
  [3, 4]
])
print(matrix_1.shape)

matrix_2 = np.array([
  [5],
  [6]
])
print(matrix_2.shape)

print(np.dot(matrix_1, matrix_2).T)

(2, 2)
(2, 1)
[[17 39]]
